apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springboot
  name: springboot
  namespace: springapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot
    spec:
      containers:
      - image: springbootk8s:0.1
        name: springbootk8s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources: {}
status: {}
